# Generated by Django 3.1.7 on 2021-04-09 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_Relation',
            fields=[
                ('relation_en', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('relation_mk', models.CharField(max_length=32)),
                ('relation_it', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=32)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvitationManager.guest_relation')),
            ],
        ),
    ]
