# Generated by Django 3.1.7 on 2021-04-11 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0002_auto_20210411_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_url_id', models.CharField(max_length=32, unique=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(null=True)),
                ('invitation_seen', models.BooleanField(default=False)),
                ('seen_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
