# Generated by Django 3.1.7 on 2021-04-11 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_Email',
            fields=[
                ('email_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_field', models.CharField(max_length=128)),
                ('cc_field', models.CharField(max_length=256)),
                ('from_field', models.CharField(max_length=128)),
                ('subject_field', models.CharField(max_length=256)),
                ('body_field', models.TextField()),
            ],
        ),
    ]
