# Generated by Django 3.1.7 on 2021-04-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0005_auto_20210411_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='group_id',
            new_name='assoc_group',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='invitation_id',
            new_name='assoc_invitation',
        ),
    ]
