# Generated by Django 3.1.7 on 2021-04-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0006_auto_20210411_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='email_id',
            new_name='assoc_email',
        ),
    ]
