# Generated by Django 3.1.7 on 2021-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0009_auto_20210425_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_public_name',
            field=models.CharField(default='Guest Group', max_length=128),
        ),
    ]
