# Generated by Django 3.1.7 on 2021-06-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0010_invitation_invitation_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_public_name',
            field=models.CharField(default='Guest Group', max_length=128),
        ),
    ]
