# Generated by Django 3.1.7 on 2021-06-14 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0011_auto_20210613_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_public_name',
        ),
    ]
