# Generated by Django 3.1.7 on 2021-11-18 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0012_remove_invitation_invitation_public_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('rsvp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_attending', models.BooleanField(default=False, null=True)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvitationManager.rsvp'),
        ),
    ]
