# Generated by Django 3.2.15 on 2022-09-18 19:19

import InvitationManager.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0013_auto_20211117_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main_config', models.BooleanField(default=False)),
                ('event_date_str', models.DateTimeField()),
                ('event_date_tz', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_url_id',
            field=models.CharField(blank=True, default=InvitationManager.models.generate_invitation_url_id, max_length=36, unique=True),
        ),
    ]
