# Generated by Django 3.2.15 on 2022-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0014_auto_20220918_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='event_date_str',
        ),
        migrations.AddField(
            model_name='config',
            name='contact_help_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='contact_help_phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_1_first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_1_full_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_1_last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_2_first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_2_full_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='partner_2_last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='reply_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='venue_addr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='venue_google_map_embed_link',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='venue_google_map_link',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='venue_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='event_date_tz',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='is_main_config',
            field=models.BooleanField(default=False, help_text='True if this is the config that has all real data. False otherwise.'),
        ),
    ]
