# Generated by Django 3.2.15 on 2022-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0015_auto_20220918_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='event_date_tz',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
