# Generated by Django 3.2.15 on 2022-09-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0016_alter_config_event_date_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logo_acronym',
            field=models.CharField(default='', help_text='Text logo to use on website. Example: P&T', max_length=6),
        ),
        migrations.AlterField(
            model_name='config',
            name='venue_google_map_embed_link',
            field=models.URLField(help_text='Embed link that Google provides in its embedded iframe.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='venue_google_map_link',
            field=models.URLField(help_text='Link to the address on Google maps.', max_length=512, null=True),
        ),
    ]
