# Generated by Django 3.2.15 on 2022-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0018_auto_20220924_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='event_date_tz_short',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='ceremony_timestamp',
            field=models.DateTimeField(help_text='In local timezone', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='event_date',
            field=models.DateTimeField(help_text='In local timezone', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='reception_timestamp',
            field=models.DateTimeField(help_text='In local timezone', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='reply_deadline',
            field=models.DateTimeField(help_text='In local timezone', null=True),
        ),
    ]
