# Generated by Django 3.2.15 on 2023-02-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0019_auto_20220924_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='event_date_tz_short',
            field=models.CharField(help_text='EST, PST, etc', max_length=8, null=True),
        ),
    ]
