# Generated by Django 3.2.15 on 2023-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0020_alter_config_event_date_tz_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_attending_ceremony',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
