# Generated by Django 3.2.15 on 2023-02-22 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0021_rsvp_is_attending_ceremony'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('related_inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvitationManager.invitation')),
            ],
        ),
    ]
