# Generated by Django 3.2.15 on 2023-03-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0022_logevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hotel_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='hotel_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
