# Generated by Django 3.2.15 on 2023-03-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0024_auto_20230308_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvitationManager.guest_relation'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='whose_guest',
            field=models.CharField(blank=True, choices=[('peter', "Peter's"), ('tea', "Teodora's"), ('tea', "Teodora's")], max_length=8, null=True),
        ),
    ]
