# Generated by Django 3.2.15 on 2023-03-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitationManager', '0025_auto_20230308_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='website_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
